## 📊 تحليل بيانات الاستماع للبودكاست
في هذا الدفتر، نقوم بتحميل البيانات، تنظيفها، تحليل سلوك المستخدمين، وأخيرًا تقديم توصيات بناءً على الأنماط.

In [2]:
import pandas as pd

# تحميل البيانات من المسارات الصحيحة
users_df = pd.read_csv("C:/Users/hessa/OneDrive/Documents/Hacker (1)_6/Desktop/8assignment/users.csv")
episodes_df = pd.read_csv("C:/Users/hessa/OneDrive/Documents/Hacker (1)_6/Desktop/8assignment/episodes.csv")
listens_df = pd.read_json("C:/Users/hessa/OneDrive/Documents/Hacker (1)_6/Desktop/8assignment/listens.json")

# عرض أول البيانات
users_df.head(), episodes_df.head(), listens_df.head()

(   user_id  age  gender       country
 0        1   38  female       Morocco
 1        2   30  female        Jordan
 2        3   42    male  Saudi Arabia
 3        4   57  female         Egypt
 4        5   51  female        Jordan,
    episode_id      title    category
 0           1  Episode 1    Religion
 1           2  Episode 2  Technology
 2           3  Episode 3     Society
 3           4  Episode 4        News
 4           5  Episode 5    Politics,
    user_id  episode_id  duration_seconds
 0       16          30                60
 1        6           8               120
 2        6          13                60
 3        6          27              1500
 4       17           9              1500)

In [3]:
# تنظيف البيانات
listens_df_cleaned = listens_df[listens_df['duration_seconds'] > 0]

# ربط البيانات
merged_df = listens_df_cleaned.merge(episodes_df, on='episode_id', how='left')
merged_df = merged_df.merge(users_df, on='user_id', how='left')

# التأكد من القيم المفقودة
print(merged_df.isnull().sum())
merged_df.head()

user_id             0
episode_id          0
duration_seconds    0
title               0
category            0
age                 0
gender              0
country             0
dtype: int64

,user_id,episode_id,duration_seconds,title,category,age,gender,country
0,16,30,60,Episode 30,Sports,24,female,Saudi Arabia
1,6,8,120,Episode 8,Sports,59,male,Morocco
2,6,13,60,Episode 13,Society,59,male,Morocco
3,6,27,1500,Episode 27,News,59,male,Morocco
4,17,9,1500,Episode 9,Sports,21,male,Saudi Arabia

In [4]:
def recommend_episodes(user_id: int, listens_df, episodes_df):
    user_listens = listens_df[listens_df['user_id'] == user_id]
    if user_listens.empty:
        return f"🚫 لا توجد استماعات للمستخدم {user_id}"
    
    top_categories = user_listens['category'].value_counts().index.tolist()
    listened_episode_ids = user_listens['episode_id'].unique()
    
    recommendations = episodes_df[episodes_df['category'].isin(top_categories)]
    recommendations = recommendations[~recommendations['episode_id'].isin(listened_episode_ids)]
    
    return recommendations.head(3)

# تجربة على مستخدم رقم 6
recommend_episodes(6, merged_df, episodes_df)

   episode_id      title  category
4           5  Episode 5  Politics
5           6  Episode 6   Society
8           9  Episode 9    Sports